
export const GET_QUESTION_AND_ANSWERS_SUCCESS="GET_QUESTION_AND_ANSWERS_SUCCESS";

export const GET_SUBJECT_ID="GET_SUBJECT_ID";

export const GET_SAVED_QUESTION_AND_ANSWERS_SUCCESS="GET_SAVED_QUESTION_AND_ANSWERS_SUCCESS";

export const GET_ON_SUBMIT_RESULT_SUCCESS="GET_ON_SUBMIT_RESULT_SUCCESS"

